services:
  postgres-db:
    image: postgres:15-alpine
    container_name: swappable-db
    environment:
      POSTGRES_DB: swappable
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\" -h localhost"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend-app:
    build: .
    container_name: swappable-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/swappable
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      BREVO_API_KEY: ${BREVO_API_KEY}
      MAIL_FROM: ${MAIL_FROM}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  pgdata: