services:
  postgres-db:
    image: postgres:15-alpine
    container_name: swappable-db
    environment:
      POSTGRES_DB: swappable
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend-app:
    build: .
    container_name: swappable-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/swappable
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: 3c9c34a2a51d428bda4c56e25f822a16d594b2a514d82bfa8c716e251b1a43a2
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - postgres-db

volumes:
  pgdata: