ALTER TABLE items ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE swap_requests ADD COLUMN requester_confirmed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE swap_requests ADD COLUMN owner_confirmed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE swap_requests ADD COLUMN completed_at TIMESTAMP;
