spring.application.name=backend

<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/swappable
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
=======
#telling java where DB is located
spring.datasource.url=jdbc:postgresql://localhost:5432/Swappable

#default username for PostgreSQL
spring.datasource.username=postgres

#replacing 'yourpassword'
spring.datasource.password=116699

#flyway tables
spring.flyway.enable=true

#lets java know how to handle tables
spring.jpo.hibernate.dd1-auto=update
spring.jpa.show-sql=true

server.port=8085

>>>>>>> f050b4d (Fixed port conflicts and updated backend to 8058)
