spring.application.name=backend

#telling java where DB is located
spring.datasource.url=jdbc:postgresql://localhost:5432/Swappable

#default username for PostgreSQL
spring.datasource.username=postgres

#replacing 'yourpassword'
spring.datasource.password=116699

#flyway tables
spring.flyway.enable=true

#lets java know how to handle tables
spring.jpa.hibernate.dd1-auto=update
spring.jpa.show-sql=true

server.port=8085


